---
- hosts: linux
  vars:
    training:
      topic: ansible
      trainer: sathish
      lab: aws
  tasks:
  - name: print dict variable
    debug:
      msg: "{{ training['topic'] }}"
  - name: print another way
    debug:
      msg: "{{ training.topic }}"
