---
- hosts: win
  tasks:
  - name: execute command on windows
    win_command: whoami
    register: output
  - debug: msg="{{output.stdout}}"
  - name: win shell
    win_shell: echo %COMPUTERNAME%
    args:
      executable: cmd
    register: output
  - debug: msg="{{output.stdout}}"
